#!/usr/bin/env python3
"""Generate the placeholder Astral guild buildings (five preset sizes).

Writes data/json/astral/settlements_guild_placeholder.json.  Run from anywhere.
"""
import json, os, sys, random
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import cddafmt
random.seed(7)
# size key: (label, W, H in OMT, city_sizes, rooms in the back wing, front-hall extras)
SIZES=[
 ("waystation","Waystation",1,1,[2,3],["bunks","kitchen"]),
 ("outpost","Outpost",1,1,[4,6],["records","kitchen","bunks"]),
 ("lodge","Lodge",2,1,[7,10],["records","kitchen","bunks","smithy","alchemy","butcher"]),
 ("hall","Hall",2,2,[11,15],["records","kitchen","bunks","smithy","alchemy","butcher","infirmary","library","tailor","bunks"]),
 ("chapterhouse","Chapterhouse",3,3,[16,55],["records","kitchen","bunks","smithy","alchemy","butcher","infirmary","library","tailor","vault","council","training","bunks","workshop"]),
]
ROOMF={ # furniture symbols used along the back wall / interior
 "records":"BBDc","kitchen":"OUUt","bunks":"bbbb","smithy":"FAWr","alchemy":"WWrL","butcher":"KKLr",
 "infirmary":"bbLD","library":"BBBc","tailor":"WWLr","vault":"LLXX","council":"TcTc","training":"rrr ","workshop":"WWWr"}
PAL={"type":"palette","id":"astral_guild_placeholder_palette",
 "//":"Placeholder guild buildings in five preset sizes (waystation, outpost, lodge, hall, chapterhouse), generated by tools/astral/gen_guild_placeholders.py.  Replaced by the Q4 guildhall art.",
 "terrain":{".":"t_region_groundcover_urban","s":"t_sidewalk","#":"t_rock_wall","w":"t_window","+":"t_door_c",",":"t_floor","_":"t_rock_floor",
   **{k:"t_floor" for k in "NTcFCBDObtUKAWrLXEP"}},
 "furniture":{"N":"f_bulletin","T":"f_table","c":"f_chair","F":"f_forge","A":"f_anvil","W":"f_workbench","r":"f_rack","L":"f_locker",
   "X":"f_crate_c","C":"f_counter","K":"f_counter","B":"f_bookcase","D":"f_desk","O":"f_woodstove","U":"f_cupboard","b":"f_bed",
   "t":"f_table","E":"f_fireplace","P":"f_bench"}}

def furnish(g,r,rx0,rx1,ry0,ry1):
    f=ROOMF[r]; k=0
    for x in range(rx0+1,rx1):
        ch=f[k%len(f)]; k+=1
        if ch!=' ': g[ry1][x]=ch
    if r in("bunks","infirmary"):
        for x in range(rx0+1,rx1,2):
            if ry1-2>ry0: g[ry1-2][x]='b'
    if r=="training":
        for y in range(ry0,ry1+1):
            for x in range(rx0,rx1+1):
                if g[y][x]==',': g[y][x]='_'

def layout(W,H,rooms):
    w,h=24*W,24*H
    g=[['.']*w for _ in range(h)]
    x0,y0,x1,y1=1,2,w-2,h-2
    for x in range(x0,x1+1): g[y0][x]='#'; g[y1][x]='#'
    for y in range(y0,y1+1): g[y][x0]='#'; g[y][x1]='#'
    for y in range(y0+1,y1):
        for x in range(x0+1,x1): g[y][x]=','
    g[y0][11]='+'; g[y0][12]='+'
    for y in range(0,y0): g[y][11]='s'; g[y][12]='s'
    for x in range(x0+3,x1-2,5):
        if g[y0][x]=='#': g[y0][x]='w'
    for y in range(y0+3,y1-2,5): g[y][x0]='w'; g[y][x1]='w'
    inner_h=y1-y0-1
    hall=min(12,inner_h-8) if H==1 else 13
    # room rows below the hall: 7 deep, separated by 2-wide corridors
    rows_avail=inner_h-hall
    nrows=max(1,(rows_avail+2)//10)
    per=-(-len(rooms)//nrows)
    y=y0+1+hall
    hall_bottom=y-1
    for ri in range(nrows):
        rr=rooms[ri*per:(ri+1)*per]
        if not rr: break
        top=y   # wall row
        depth=7 if ri<nrows-1 else (y1-1-top)
        bottom=top+depth
        for x in range(x0,x1+1): g[top][x]='#'
        n=len(rr); inner_w=x1-x0-1; rw=inner_w//n
        for i,r in enumerate(rr):
            rx0=x0+1+i*rw; rx1=(x0+inner_w if i==n-1 else rx0+rw-1)
            if i>0:
                for yy in range(top,bottom+1): g[yy][rx0-1]='#'
            g[top][(rx0+rx1)//2]='+'
            furnish(g,r,rx0,rx1,top+1,bottom)
        if ri<nrows-1:
            # wall closing this row, then a corridor, then the next row's wall
            for x in range(x0,x1+1): g[bottom+1][x]='#'
            # rooms in this row also open south onto the corridor
            for i in range(n):
                rx0=x0+1+i*rw; rx1=(x0+inner_w if i==n-1 else rx0+rw-1)
                g[bottom+1][(rx0+rx1)//2]='+'
            y=bottom+4
            # corridor rows bottom+2, bottom+3 stay floor; link it to the hall at both ends
            for yy in range(top,bottom+2):
                g[yy][x0+1]=',' if yy!=top else '+'
        else:
            break
    hy0,hy1=y0+1,hall_bottom
    g[hy0][x0+1]='N'; g[hy0][x1-1]='N'; g[hy0+1][x0+1]='N'
    cy=hy1-1
    for x in range(x0+2,min(x0+9,x1-1)): g[cy][x]='C'
    for x in range(max(x1-8,x0+10),x1-1): g[cy][x]='C'
    for ty in range(hy0+3,cy-2,3):
        for tx in range(x0+4,x1-4,6):
            if g[ty][tx]==',' and g[ty][tx+2]==',':
                g[ty][tx]='c'; g[ty][tx+1]='T'; g[ty][tx+2]='c'
    fx=(x0+x1)//2
    if g[hy0][fx]==',': g[hy0][fx]='E'
    return ["".join(r) for r in g]

out=[PAL]
for key,label,W,H,cs,rooms in SIZES:
    oid="astral_guild_"+key
    rows=layout(W,H,rooms)
    grid=[[f"{oid}_{x}_{y}" for x in range(W)] for y in range(H)]
    for y in range(H):
        for x in range(W):
            out.append({"type":"overmap_terrain","id":grid[y][x],"name":"Astral Guild "+label,"sym":"G","color":"light_blue","see_cost":"medium","extras":"build","mondensity":2})
    out.append({"type":"city_building","id":oid,"locations":["land"],
                "overmaps":[{"point":[x,y,0],"overmap":grid[y][x]+"_north"} for y in range(H) for x in range(W)],
                "city_sizes":cs,"flags":["CITY_UNIQUE"]})
    out.append({"type":"mapgen","om_terrain":grid if (W>1 or H>1) else grid[0][0],
                "object":{"fill_ter":"t_floor","rows":rows,"palettes":["astral_guild_placeholder_palette"],
                          "place_signs":[{"signage":f"Astral Guild – {label}.  Contracts posted daily.","x":9,"y":0}]}})
    print(key, W,"x",H, "towns",cs, "rooms",len(rooms))
    if key in("hall",):
        print("\n".join(rows))
open(os.path.join(HERE, '..', '..', 'data', 'json', 'astral', 'settlements_guild_placeholder.json'),'w').write(cddafmt.fmt(out,0,0)+"\n")
