#!/usr/bin/env python3
"""Compile the T4 sprite-job list (staged plan WP-E7) from the content lists and the Craft.

Writes claude/plans/astral-sprite-jobs.md: one row per item, creature, plant and vein that
has no sprite yet, with a prompt built from the row's 'look' column in Astra's icon style,
the looks_like fallback the game uses meanwhile, and a priority (critical rows and the
Craft's foci/grimoires first).  Astra runs the batches; nothing here touches art.

    python3 tools/astral/gen_sprite_jobs.py
"""
import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "tools", "astral"))
import gen_content  # noqa: E402

OUT = os.path.join(ROOT, "claude", "plans", "astral-sprite-jobs.md")
STYLE = "pixel art icon, top-down three-quarter view, flat lighting, high-contrast silhouette, simple large shapes, transparent background"


def main():
    data = gen_content.load_lists()
    items = {e["id"]: e for e in json.load(open(os.path.join(ROOT, "data", "json", "astral", "content", "items.json"))) if "id" in e}
    magic = json.load(open(os.path.join(ROOT, "data", "json", "astral", "magic", "items.json")))
    magic += json.load(open(os.path.join(ROOT, "data", "json", "astral", "magic", "grimoires.json")))
    rows = []
    for r in data["items"]:
        look = r.get("look (≤ 12 words)", "").strip()
        pr = "critical" if r.get("critical", "").strip().upper().startswith("Y") else ("normal" if r.get("kind") in ("raw", "intermediate") else "later")
        rows.append((pr, r["id"], "item", r.get("cell", "32") or "32", f"one single {look}, {STYLE}", items.get(r["id"], {}).get("looks_like") or items.get(r["id"], {}).get("copy-from", "—")))
    for e in magic:
        if e.get("type") != "ITEM":
            continue
        look = e.get("description", "").split(".")[0].lower()
        rows.append(("normal", e["id"], "item", "32", f"one single {look}, {STYLE}", e.get("looks_like", "—")))
    for r in data["creatures"]:
        look = r.get("look (≤ 12 words)", "").strip()
        rows.append(("normal" if int((r.get("rank") or "1")[0]) >= 3 else "later", r["id"], "monster", "64",
                     f"one single {look}, full body, {STYLE}", r.get("base (vanilla copy-from)", "—")))
    for r in data["flora"]:
        look = r.get("look (≤ 12 words)", "").strip()
        rows.append(("normal", r["id"], "terrain/furniture", r.get("cell", "32") or "32", f"{look}, seen from above, {STYLE}", "vanilla look-alike"))
    order = {"critical": 0, "normal": 1, "later": 2}
    rows.sort(key=lambda t: (order[t[0]], t[1]))
    counts = {k: sum(1 for t in rows if t[0] == k) for k in order}
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("# Astral sprite jobs (T4, compiled)\n\n")
        fh.write("Generated by `tools/astral/gen_sprite_jobs.py` from the content lists and the Craft — do not edit by hand. "
                 f"{len(rows)} jobs: {counts['critical']} critical, {counts['normal']} normal, {counts['later']} later. "
                 "Every id ships on its `looks_like` until a sprite lands. Astra owns the art and the style "
                 "(`claude/handoffs/grok-2026-10-02-icon-style-guide.md`); prompts here are starting points.\n\n")
        fh.write("| id | kind | cell | prompt | looks_like fallback | priority |\n| --- | --- | --- | --- | --- | --- |\n")
        for pr, i, kind, cell, prompt, fb in rows:
            fh.write(f"| {i} | {kind} | {cell} | {prompt.replace('|', '/')} | {fb} | {pr} |\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(rows)} jobs {counts}")


if __name__ == "__main__":
    main()
