"""Deterministic lowland templates: shallow water, rounded islands, inset depths."""
import math
import random
from collections import deque


def water_mask(seed, size=24):
    rng = random.Random(seed)
    # Three irregular elliptical hummocks; all edges remain wadeable water.
    centres = [(6, 6), (17, 8), (11, 18)]
    islands = [(x + rng.uniform(-2, 2), y + rng.uniform(-2, 2),
                rng.uniform(2.3, 3.3), rng.uniform(2.2, 3.2), rng.random() * math.tau)
               for x, y in centres]
    land = set()
    for y in range(2, size - 2):
        for x in range(2, size - 2):
            for cx, cy, rx, ry, phase in islands:
                angle = math.atan2(y - cy, x - cx)
                wobble = 1 + .14 * math.sin(angle * 3 + phase)
                if ((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2 < wobble:
                    land.add((x, y))
                    break
    # Treat the boundary as distance zero too: deep water never reaches a map edge.
    distance = {(x, y): 0 for y in range(size) for x in range(size)
                if (x, y) in land or x in (0, size-1) or y in (0, size-1)}
    queue = deque(distance)
    while queue:
        x, y = queue.popleft()
        for nx, ny in ((x-1, y), (x+1, y), (x, y-1), (x, y+1)):
            if 0 <= nx < size and 0 <= ny < size and (nx, ny) not in distance:
                distance[nx, ny] = distance[x, y] + 1
                queue.append((nx, ny))
    rows = ["".join("m" if (x, y) in land else "w" if distance[x, y] >= 4 else "~"
                    for x in range(size)) for y in range(size)]
    # Existing 4x4 flora/vein chunks may only replace land, never the depth collar.
    scatter = [(x, y) for y in range(size-3) for x in range(size-3)
               if all((x+dx, y+dy) in land for dx in range(4) for dy in range(4))]
    return rows, scatter[::max(1, len(scatter)//3)][:3]


def templates(count=8):
    result = []
    for seed in range(count):
        rows, scatter = water_mask(seed)
        obj = {"mapgensize": [24, 24], "rows": rows,
               "terrain": {"~": "t_water_sh", "w": "t_water_dp",
                           "m": [["t_mud", 8], ["t_grass_long", 2], ["t_grass_tall", 1]]}}
        if scatter:
            obj["place_nested"] = [{"chunks": [["astral_scatter_drowned", 1]], "x": x, "y": y}
                                   for x, y in scatter]
        result.append({"type": "mapgen", "nested_mapgen_id": f"astral_depth_lowland_{seed}",
                       "//": "Generated by gen_biome.py; deep cells are inset four tiles from land and edges.",
                       "object": obj})
    return result
